name: Build - Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Install dependancies
      run: |
         npm install --save-dev electron-packager
         npm install
    - name: Building
      run: npm run build
    - name: Compressing
      run: |
        ls -alh build/the-power-ui-darwin-x64
        pwd
        tar -czvf the-power-ui.app.tar.gz build/the-power-ui-darwin-x64/the-power-ui.app
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: true
         title: "Initial build"
         files: |
            the-power-ui.app.tar.gz
