name: Build - Release

on:
  workflow_dispatch:
    inputs:
      pre-release:
        description: "Pre-release"
        type: boolean
        default: true
      tag:
        description: "Tag"
        default: "latest"
        required: true
      title:
        description: "Release Title"
        default: "The-Power-UI"
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - name: Install dependancies
      run: |
         npm install --save-dev electron-packager
         npm install
    - name: Building
      run: npm run build
    - name: Compressing
      run: |
        ls -alh build/the-power-ui-darwin-x64
        pwd
        tar -czvf the-power-ui.app.tar.gz build/the-power-ui-darwin-x64/the-power-ui.app
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "${{ inputs.tag }}"
         prerelease: "${{ inputs.pre-release }}"
         title: "${{ inputs.title }}"
         files: |
            the-power-ui.app.tar.gz
